In [18]:
import pandas as pd
import numpy as np

movies = pd.read_csv("../data/TMDB_movie_dataset_v11.csv")

In [19]:
movies.head()

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_title,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,Inception,"Cobb, a skilled thief who commits corporate es...",83.952,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc..."
1,157336,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,...,Interstellar,The adventures of a group of explorers who mak...,140.241,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,..."
2,155,The Dark Knight,8.512,30619,Released,2008-07-16,1004558444,152,False,/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg,...,The Dark Knight,Batman raises the stakes in his war on crime. ...,130.643,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,Welcome to a world without rules.,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f..."
3,19995,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,...,Avatar,"In the 22nd century, a paraplegic Marine is di...",79.932,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,Enter the world of Pandora.,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ..."
4,24428,The Avengers,7.710,29166,Released,2012-04-25,1518815515,143,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,...,The Avengers,When an unexpected enemy emerges and threatens...,98.082,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,Some assembly required.,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com..."

In [20]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1373291 entries, 0 to 1373290
Data columns (total 24 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   id                    1373291 non-null  int64
 1   title                 1373273 non-null  object
 2   vote_average          1373291 non-null  float64
 3   vote_count            1373291 non-null  int64
 4   status                1373291 non-null  object
 5   release_date          1080593 non-null  object
 6   revenue               1373291 non-null  int64
 7   runtime               1373291 non-null  int64
 8   adult                 1373291 non-null  bool
 9   backdrop_path         344781 non-null   object
 10  budget                1373291 non-null  int64
 11  homepage              141796 non-null   object
 12  imdb_id               657699 non-null   object
 13  original_language     1373291 non-null  object
 14  original_title        1373273 non-null  object
 15  overview              1062203 non-null  object
 16  popularity            1373291 non-null  float64
 17  poster_path           894025 non-null   object
 18  tagline               191267 non-null   object
 19  genres                777297 non-null   object
 20  production_companies  589918 non-null   object
 21  production_countries  716808 non-null   object
 22  spoken_languages      742504 non-null   object
 23  keywords              343862 non-null   object
dtypes: bool(1), float64(2), int64(5), object(16)
memory usage: 242.3+ MB

In [21]:
movies.columns

Index(['id', 'title', 'vote_average', 'vote_count', 'status', 'release_date',
       'revenue', 'runtime', 'adult', 'backdrop_path', 'budget', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'tagline', 'genres',
       'production_companies', 'production_countries', 'spoken_languages',
       'keywords'],
      dtype='object')

In [22]:
columns_to_drop = ['adult', 'budget', 'backdrop_path', 'homepage', 'imdb_id', 'runtime', 'popularity', 'revenue', 'vote_average', 'vote_count', 'original_language']

df = movies.drop(columns=columns_to_drop, axis = 1)
df.head(1)

,id,title,status,release_date,original_title,overview,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
0,27205,Inception,Released,2010-07-15,Inception,"Cobb, a skilled thief who commits corporate es...",/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc..."

In [23]:
df.isnull().sum()

id                            0
title                        18
status                        0
release_date             292698
original_title               18
overview                 311088
poster_path              479266
tagline                 1182024
genres                   595994
production_companies     783373
production_countries     656483
spoken_languages         630787
keywords                1029429
dtype: int64

In [24]:
df.duplicated().sum()

np.int64(444)

In [25]:
df.dropna(subset = 'title', inplace = True)
df.drop_duplicates(subset = 'title', inplace = True)
df.dropna(subset = 'overview', inplace = True)
df.drop_duplicates(subset = 'overview', inplace = True)
df.dropna(subset = 'poster_path', inplace = True)
df.drop_duplicates(subset = 'poster_path', inplace = True)
df.dropna(subset = 'release_date', inplace = True)

In [26]:
df.isnull().sum()

id                           0
title                        0
status                       0
release_date                 0
original_title               0
overview                     0
poster_path                  0
tagline                 447442
genres                  166027
production_companies    228517
production_countries    180906
spoken_languages        161693
keywords                351479
dtype: int64

In [27]:
df.shape

(563792, 13)

In [28]:
def preprocess_tags(text, separator=' '):
    if not isinstance(text, str):
        text = str(text)

    text = text.lower()
    texts = text.split(separator)
    
    return ' '.join([t.replace(' ', '') for t in texts])

df['genres'] = df['genres'].apply(preprocess_tags, separator = ',')
df['production_companies'] = df['production_companies'].apply(preprocess_tags, separator = ',')
df['production_countries'] = df['production_countries'].apply(preprocess_tags, separator = ',')
df['spoken_languages'] = df['spoken_languages'].apply(preprocess_tags, separator = ',')
df['keywords'] = df['keywords'].apply(preprocess_tags, separator = ',')
df['overview'] = df['overview'].apply(preprocess_tags)

df.head(1)

,id,title,status,release_date,original_title,overview,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
0,27205,Inception,Released,2010-07-15,Inception,"cobb, a skilled thief who commits corporate es...",/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,action sciencefiction adventure,legendarypictures syncopy warnerbros.pictures,unitedkingdom unitedstatesofamerica,english french japanese swahili,rescue mission dream airplane paris france vir...

In [29]:
cols = [
    'title', 'tagline', 'genres', 'keywords', 'overview',
    # 'production_companies', 'production_countries', 'spoken_languages'
]

df['all_tags'] = df[cols].astype(str).agg(' '.join, axis=1)
df['all_tags'] = df['all_tags'].apply(lambda x: x.lower())

final_df = df[['id', 'title', 'poster_path', 'all_tags', 'release_date', 'status']].copy()
final_df['all_tags'] = final_df['all_tags'].apply(lambda x: x.split())
final_df.head(1)

,id,title,poster_path,all_tags,release_date,status
0,27205,Inception,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,"[inception, your, mind, is, the, scene, of, th...",2010-07-15,Released

In [30]:
final_df['all_tags'][0]

['inception',
 'your',
 'mind',
 'is',
 'the',
 'scene',
 'of',
 'the',
 'crime.',
 'action',
 'sciencefiction',
 'adventure',
 'rescue',
 'mission',
 'dream',
 'airplane',
 'paris',
 'france',
 'virtualreality',
 'kidnapping',
 'philosophy',
 'spy',
 'allegory',
 'manipulation',
 'carcrash',
 'heist',
 'memory',
 'architecture',
 'losangeles',
 'california',
 'dreamworld',
 'subconscious',
 'cobb,',
 'a',
 'skilled',
 'thief',
 'who',
 'commits',
 'corporate',
 'espionage',
 'by',
 'infiltrating',
 'the',
 'subconscious',
 'of',
 'his',
 'targets',
 'is',
 'offered',
 'a',
 'chance',
 'to',
 'regain',
 'his',
 'old',
 'life',
 'as',
 'payment',
 'for',
 'a',
 'task',
 'considered',
 'to',
 'be',
 'impossible:',
 '"inception",',
 'the',
 'implantation',
 'of',
 'another',
 "person's",
 'idea',
 'into',
 'a',
 "target's",
 'subconscious.']

In [ ]:
import nltk, re
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('stopwords')

stop_words = set(stopwords.words('english'))

_pattern = re.compile(r"[^a-z0-9\s]")

def clean_tags(tags):
    if not isinstance(tags, list):
        return ""
    
    cleaned = [
        token
        for tag in tags
        for token in _pattern.sub("", tag.lower()).split()
        if token and token not in stop_words
    ]

    return " ".join(cleaned)

# print(clean_tags(final_df['all_tags'][0]))

final_df['all_tags'] = final_df['all_tags'].apply(clean_tags)

[nltk_data] Downloading package punkt to /Users/pheonix-
[nltk_data]     fire/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /Users/pheonix-
[nltk_data]     fire/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [32]:
final_df.head()

,id,title,poster_path,all_tags,release_date,status
0,27205,Inception,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,inception mind scene crime action scienceficti...,2010-07-15,Released
1,157336,Interstellar,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,interstellar mankind born earth never meant di...,2014-11-05,Released
2,155,The Dark Knight,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,dark knight welcome world without rules drama ...,2008-07-16,Released
3,19995,Avatar,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,avatar enter world pandora action adventure fa...,2009-12-15,Released
4,24428,The Avengers,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,avengers assembly required sciencefiction acti...,2012-04-25,Released

In [33]:
final_df['release_date'] = final_df['release_date'].astype('object')

final_df['year'] = final_df['release_date'].apply(lambda x : x[:4]).astype(int)

final_df = final_df[final_df['year'] >= 1975]
final_df.sort_values(by = 'year')

final_df = final_df[(final_df['status'] == 'Released')]

print(final_df.shape)
final_df.head()

(481782, 7)

,id,title,poster_path,all_tags,release_date,status,year
0,27205,Inception,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,inception mind scene crime action scienceficti...,2010-07-15,Released,2010
1,157336,Interstellar,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,interstellar mankind born earth never meant di...,2014-11-05,Released,2014
2,155,The Dark Knight,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,dark knight welcome world without rules drama ...,2008-07-16,Released,2008
3,19995,Avatar,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,avatar enter world pandora action adventure fa...,2009-12-15,Released,2009
4,24428,The Avengers,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,avengers assembly required sciencefiction acti...,2012-04-25,Released,2012

In [34]:
from src.constants import PREPROCESSED_DATASET_PATH

final_df.to_csv(f'../data/preprocessed_dataset.csv', index = False)