In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv('../data/preprocessed_dataset.csv')

In [3]:
df.head()

,id,title,poster_path,all_tags,release_date,year
0,27205,Inception,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,cobb a skill thief who commit corpor espionag ...,2010-07-15,2010
1,157336,Interstellar,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,the adventur of a group of explor who make use...,2014-11-05,2014
2,155,The Dark Knight,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,batman rais the stake in his war on crime with...,2008-07-16,2008
3,19995,Avatar,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,in the 22nd centuri a parapleg marin is dispat...,2009-12-15,2009
4,24428,The Avengers,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,when an unexpect enemi emerg and threaten glob...,2012-04-25,2012

In [4]:
print(df.isnull().sum())
df.dropna(inplace=True)
print(df.isnull().sum())

id              0
title           0
poster_path     0
all_tags        0
release_date    0
year            0
dtype: int64
id              0
title           0
poster_path     0
all_tags        0
release_date    0
year            0
dtype: int64

In [5]:
df.describe()

                 id           year
count  4.851010e+05  485101.000000
mean   7.372983e+05    2010.633297
std    4.342281e+05      12.434559
min    2.000000e+00    1975.000000
25%    4.057740e+05    2005.000000
50%    7.054790e+05    2015.000000
75%    1.067744e+06    2020.000000
max    1.618179e+06    2099.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 485101 entries, 0 to 485100
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            485101 non-null  int64
 1   title         485101 non-null  object
 2   poster_path   485101 non-null  object
 3   all_tags      485101 non-null  object
 4   release_date  485101 non-null  object
 5   year          485101 non-null  int64
dtypes: int64(2), object(4)
memory usage: 22.2+ MB

In [7]:
df.shape

(485101, 6)

In [8]:
vocabulary = set().union(*df['all_tags'].str.split())
len(vocabulary)

362035

In [9]:
# Text Vectorization
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(stop_words='english')
            
vectors = tfidf.fit_transform(df['all_tags'])
vectors

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 15202922 stored elements and shape (485101, 361715)>

In [11]:
tfidf.get_feature_names_out()

array(['00', '000', '0000', ..., 'zzyzx', 'zzzax', 'zzzz'],
      shape=(361715,), dtype=object)

In [12]:
df[['id','title']]

            id                                              title
0        27205                                          Inception
1       157336                                       Interstellar
2          155                                    The Dark Knight
3        19995                                             Avatar
4        24428                                       The Avengers
...        ...                                                ...
485096  875790  Juice=Juice LIVE 2018 at NIPPON BUDOKAN TRIANG...
485097  875795  Flickers: Gay Themed Theatrical Trailers from ...
485098  875797                             Film sur Georges Perec
485099  875799                                               Kori
485100  875801                                Mrs. Vera's Daybook

[485101 rows x 2 columns]

In [14]:
from sklearn.metrics.pairwise import cosine_similarity

top_k = 10
row_idx = df.index[df['id'] == 24428][0]
sim = cosine_similarity(vectors[row_idx], vectors).flatten()
top_indices = np.argsort(sim)[-top_k-1:-1][::-1]

df.iloc[top_indices]['title']

406526                           Avengers: The Kang Dynasty
443253                     Captain America: Brave New World
406527                                Avengers: Secret Wars
34                           Guardians of the Galaxy Vol. 2
15539                           Inhumans: The First Chapter
6704      Marvel One-Shot: A Funny Thing Happened on the...
441                                                Eternals
116                                          Captain Marvel
5988                                              Team Thor
12459                 Marvel Studios: Assembling a Universe
Name: title, dtype: object

In [ ]:
# def recommend_top_n_movies(top_n : int, movie_name : str):
#     if movie_name not in new_df['title'].values:
#         print(f"Movie '{movie_name}' not found in the database.")
#         return
#     movie_index = new_df[new_df['title'] == movie_name].index[0]
#     distances = similarity[movie_index]
#     movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:top_n+1]
    
#     for i in movies_list:
#         print(new_df.iloc[i[0]].title)


# recommend_top_n_movies(5, 'Fight Club')

In [ ]:
movies_map = df.set_index('id')['title'].to_dict()

movies_map = sorted(movies_map.items(), key = lambda x : x[1])

# with open("../src/constants/__init__.py", "a", encoding="utf-8") as f:
#     f.write('{')
#     for k, v in movies_map:
#         f.write(f'''    {k}: "{v.replace('"', '')}",\n''')
#     f.write('} # type: ignore')

In [ ]:
for index in [2518.0, 11214.0, 17665.0, 17663.0, 15882.0, 18517.0, 18515.0, 13716.0, 26225.0, 18448.0]:
    print(df[df.index == index]['title'])

2518    Toy Story 2
Name: title, dtype: object
11214    Dhoondte Reh Jaoge
Name: title, dtype: object
17665    Charlotte's Web 2: Wilbur's Great Adventure
Name: title, dtype: object
17663    Copenhagen
Name: title, dtype: object
15882    Ender's Game
Name: title, dtype: object
18517    The Invisible Boy
Name: title, dtype: object
18515    Ghost Son
Name: title, dtype: object
13716    A Map For Saturday
Name: title, dtype: object
26225    Details
Name: title, dtype: object
18448    Let's Kill Ward's Wife
Name: title, dtype: object