In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('../data/preprocessed_dataset.csv')

In [2]:
df.head()

,id,title,poster_path,all_tags,release_date,status,year
0,27205,Inception,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,inception mind scene crime action scienceficti...,2010-07-15,Released,2010
1,157336,Interstellar,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,interstellar mankind born earth never meant di...,2014-11-05,Released,2014
2,155,The Dark Knight,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,dark knight welcome world without rules drama ...,2008-07-16,Released,2008
3,19995,Avatar,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,avatar enter world pandora action adventure fa...,2009-12-15,Released,2009
4,24428,The Avengers,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,avengers assembly required sciencefiction acti...,2012-04-25,Released,2012

In [3]:
print(df.isnull().sum())
df.dropna(inplace=True)
print(df.isnull().sum())

id              0
title           0
poster_path     0
all_tags        0
release_date    0
status          0
year            0
dtype: int64
id              0
title           0
poster_path     0
all_tags        0
release_date    0
status          0
year            0
dtype: int64

In [4]:
df.describe()

                 id           year
count  4.817820e+05  481782.000000
mean   7.348035e+05    2010.491287
std    4.351259e+05      12.419656
min    2.000000e+00    1975.000000
25%    4.028312e+05    2005.000000
50%    7.014465e+05    2015.000000
75%    1.061761e+06    2020.000000
max    1.637517e+06    2057.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 481782 entries, 0 to 481781
Data columns (total 7 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            481782 non-null  int64
 1   title         481782 non-null  object
 2   poster_path   481782 non-null  object
 3   all_tags      481782 non-null  object
 4   release_date  481782 non-null  object
 5   status        481782 non-null  object
 6   year          481782 non-null  int64
dtypes: int64(2), object(5)
memory usage: 25.7+ MB

In [6]:
df.shape

(481782, 7)

In [7]:
vocabulary = set().union(*df['all_tags'].str.split())
len(vocabulary)

584413

In [8]:
# Text Vectorization
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(stop_words='english')

vectors = tfidf.fit_transform(df['all_tags'])
vectors

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 14852194 stored elements and shape (481782, 584188)>

In [9]:
tfidf.get_feature_names_out()

array(['00', '000', '0000', ..., 'zzzaxs', 'zzzoe', 'zzzz'],
      shape=(584188,), dtype=object)

In [10]:
df[['id','title']]

            id                                           title
0        27205                                       Inception
1       157336                                    Interstellar
2          155                                 The Dark Knight
3        19995                                          Avatar
4        24428                                    The Avengers
...        ...                                             ...
481777  883746  El delantero centro fue asesinado al atardecer
481778  883747                                        Lollygag
481779  883754                               Bad Sister-in-law
481780  883756                          La soledad del manager
481781  883757                                 Tal como éramos

[481782 rows x 2 columns]

In [11]:
df[df['title'] == 'Toy Story']

,id,title,poster_path,all_tags,release_date,status,year
72,862,Toy Story,/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg,toy story hang comedy goes infinity beyond ani...,1995-10-30,Released,1995

In [16]:
from sklearn.metrics.pairwise import cosine_similarity

top_k = 10
row_idx = df.index[df['id'] == 862][0]
sim = cosine_similarity(vectors[row_idx], vectors).flatten()
top_indices = np.argsort(sim)[-top_k-1:-1][::-1]

df.iloc[top_indices]['title']

158                                            Toy Story 2
137                                            Toy Story 3
9866     Beyond Infinity: Buzz and the Journey to Light...
7951     Buzz Lightyear of Star Command: The Adventure ...
325                                            Toy Story 4
58019                                     Tiny Toy Stories
5852                                             Small Fry
1411                                             Lightyear
44773                       Pixar 2021 Disney+ Day Special
22816                              Mr. Incredible and Pals
Name: title, dtype: object

In [13]:
# def recommend_top_n_movies(top_n : int, movie_name : str):
#     if movie_name not in new_df['title'].values:
#         print(f"Movie '{movie_name}' not found in the database.")
#         return
#     movie_index = new_df[new_df['title'] == movie_name].index[0]
#     distances = similarity[movie_index]
#     movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:top_n+1]
    
#     for i in movies_list:
#         print(new_df.iloc[i[0]].title)


# recommend_top_n_movies(5, 'Fight Club')

In [14]:
movies_map = df.set_index('id')['title'].to_dict()

movies_map = sorted(movies_map.items(), key = lambda x : x[1])

# with open("../src/constants/__init__.py", "a", encoding="utf-8") as f:
#     f.write('{')
#     for k, v in movies_map:
#         f.write(f'''    {k}: "{v.replace('"', '')}",\n''')
#     f.write('} # type: ignore')

In [15]:
for index in [2518.0, 11214.0, 17665.0, 17663.0, 15882.0, 18517.0, 18515.0, 13716.0, 26225.0, 18448.0]:
    print(df[df.index == index]['title'])

2518    In the Name of the Father
Name: title, dtype: object
11214    Ae Dil Hai Mushkil
Name: title, dtype: object
17665    Easy
Name: title, dtype: object
17663    Scandal Makers
Name: title, dtype: object
15882    Avenue Montaigne
Name: title, dtype: object
18517    The Trench
Name: title, dtype: object
18515    Bibi Blocksberg
Name: title, dtype: object
13716    The Electric Horseman
Name: title, dtype: object
26225    Raja Rani
Name: title, dtype: object
18448    Gyo: Tokyo Fish Attack
Name: title, dtype: object