In [16]:
import pandas as pd
import numpy as np

df = pd.read_csv('../data/preprocessed_dataset.csv')

In [17]:
df.head()

,id,title,poster_path,all_tags,release_date,status,year
0,27205,Inception,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,inception action sciencefiction adventure resc...,2010-07-15,Released,2010
1,157336,Interstellar,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,interstellar adventure drama sciencefiction re...,2014-11-05,Released,2014
2,155,The Dark Knight,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,dark knight drama action crime thriller joker ...,2008-07-16,Released,2008
3,19995,Avatar,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,avatar action adventure fantasy sciencefiction...,2009-12-15,Released,2009
4,24428,The Avengers,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,avengers sciencefiction action adventure newyo...,2012-04-25,Released,2012

In [18]:
print(df.isnull().sum())
df.dropna(inplace=True)
print(df.isnull().sum())

id              0
title           0
poster_path     0
all_tags        0
release_date    0
status          0
year            0
dtype: int64
id              0
title           0
poster_path     0
all_tags        0
release_date    0
status          0
year            0
dtype: int64

In [19]:
df.describe()

                 id           year
count  4.048270e+05  404827.000000
mean   6.908589e+05    2010.094542
std    4.291418e+05      12.797000
min    2.000000e+00    1975.000000
25%    3.506270e+05    2004.000000
50%    6.541330e+05    2014.000000
75%    1.014456e+06    2020.000000
max    1.627358e+06    2057.000000

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 404827 entries, 0 to 404826
Data columns (total 7 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            404827 non-null  int64
 1   title         404827 non-null  object
 2   poster_path   404827 non-null  object
 3   all_tags      404827 non-null  object
 4   release_date  404827 non-null  object
 5   status        404827 non-null  object
 6   year          404827 non-null  int64
dtypes: int64(2), object(5)
memory usage: 21.6+ MB

In [21]:
df.shape

(404827, 7)

In [22]:
vocabulary = set().union(*df['all_tags'].str.split())
len(vocabulary)

442469

In [23]:
# Text Vectorization
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(stop_words='english')

vectors = tfidf.fit_transform(df['all_tags'])
vectors

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 11555548 stored elements and shape (404827, 442245)>

In [24]:
tfidf.get_feature_names_out()

array(['00', '000', '0000', ..., 'zzzaxs', 'zzzoe', 'zzzz'],
      shape=(442245,), dtype=object)

In [25]:
df[['id','title']]

            id                  title
0        27205              Inception
1       157336           Interstellar
2          155        The Dark Knight
3        19995                 Avatar
4        24428           The Avengers
...        ...                    ...
404822  843867                Erêkauã
404823  843835  The Feel at the Wheel
404824  843842           Sundown Town
404825  843857    Being Black in Porn
404826  843861                 Horner

[404827 rows x 2 columns]

In [26]:
df[df['title'] == 'Toy Story']

,id,title,poster_path,all_tags,release_date,status,year
72,862,Toy Story,/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg,toy story animation adventure family comedy re...,1995-10-30,Released,1995

In [27]:
from sklearn.metrics.pairwise import cosine_similarity

top_k = 10
row_idx = df.index[df['id'] == 155][0]
sim = cosine_similarity(vectors[row_idx], vectors).flatten()
top_indices = np.argsort(sim)[-top_k-1:-1][::-1]

df.iloc[top_indices]['title']

476                                     Batman
2710                Batman: Under the Red Hood
5618      Batman: The Long Halloween, Part One
6346      Batman: The Long Halloween, Part Two
25                       The Dark Knight Rises
3793              Batman: Mask of the Phantasm
46156                         Batman: Dead End
242946                   Batman: Dying is Easy
41                               Batman Begins
358                                 The Batman
Name: title, dtype: object

In [28]:
# def recommend_top_n_movies(top_n : int, movie_name : str):
#     if movie_name not in new_df['title'].values:
#         print(f"Movie '{movie_name}' not found in the database.")
#         return
#     movie_index = new_df[new_df['title'] == movie_name].index[0]
#     distances = similarity[movie_index]
#     movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:top_n+1]
    
#     for i in movies_list:
#         print(new_df.iloc[i[0]].title)


# recommend_top_n_movies(5, 'Fight Club')

In [29]:
movies_map = df.set_index('id')['title'].to_dict()

movies_map = sorted(movies_map.items(), key = lambda x : x[1])

# with open("../src/constants/__init__.py", "a", encoding="utf-8") as f:
#     f.write('{')
#     for k, v in movies_map:
#         f.write(f'''    {k}: "{v.replace('"', '')}",\n''')
#     f.write('} # type: ignore')

In [30]:
for index in [2518.0, 11214.0, 17665.0, 17663.0, 15882.0, 18517.0, 18515.0, 13716.0, 26225.0, 18448.0]:
    print(df[df.index == index]['title'])

2518    In the Name of the Father
Name: title, dtype: object
11214    Killers Anonymous
Name: title, dtype: object
17665    Shiver
Name: title, dtype: object
17663    Madres
Name: title, dtype: object
15882    Curtains
Name: title, dtype: object
18517    Eyyvah Eyvah 2
Name: title, dtype: object
18515    The Family That Preys
Name: title, dtype: object
13716    The Lonely Guy
Name: title, dtype: object
26225    Tortilla Soup
Name: title, dtype: object
18448    The Ghazi Attack
Name: title, dtype: object