In [1]:
import pandas as pd
import numpy as np
from src.constants import PREPROCESSED_DATASET_PATH

df = pd.read_csv('../data/preprocessed_dataset.csv')

In [2]:
df.head()

,id,title,all_tags,release_date,year
0,862,Toy Story,led by woodi andi toy live happili in his room...,1995-10-30,1995
1,8844,Jumanji,when sibl judi and peter discov an enchant boa...,1995-12-15,1995
2,15602,Grumpier Old Men,a famili wed reignit the ancient feud between ...,1995-12-22,1995
3,31357,Waiting to Exhale,cheat on mistreat and step on the women are ho...,1995-12-22,1995
4,11862,Father of the Bride Part II,just when georg bank has recov from his daught...,1995-02-10,1995

In [3]:
print(df.isnull().sum())
df.dropna(inplace=True)
print(df.isnull().sum())

id               0
title            0
all_tags        11
release_date     0
year             0
dtype: int64
id              0
title           0
all_tags        0
release_date    0
year            0
dtype: int64

In [4]:
df.describe()

                  id          year
count   32831.000000  32831.000000
mean   114435.178338   2002.760470
std    119469.681616     11.173015
min         2.000000   1975.000000
25%     23628.500000   1996.000000
50%     60175.000000   2006.000000
75%    179907.000000   2012.000000
max    469172.000000   2020.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32831 entries, 0 to 32841
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            32831 non-null  int64
 1   title         32831 non-null  object
 2   all_tags      32831 non-null  object
 3   release_date  32831 non-null  object
 4   year          32831 non-null  int64
dtypes: int64(2), object(3)
memory usage: 1.5+ MB

In [6]:
df.shape

(32831, 5)

In [7]:
vocabulary = set().union(*df['all_tags'].str.split())
len(vocabulary)

153097

In [8]:
# Text Vectorization
from sklearn.feature_extraction.text import CountVectorizer 
cv = CountVectorizer(max_features=len(vocabulary), stop_words='english')

vectors = cv.fit_transform(df['all_tags'])
vectors

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2149694 stored elements and shape (32831, 152798)>

In [9]:
cv.get_feature_names_out()

array(['00', '000', '001', ..., 'zzraku', 'zzvorkov', 'zzzax'],
      shape=(152798,), dtype=object)

In [10]:
df[['id','title']]

           id                        title
0         862                    Toy Story
1        8844                      Jumanji
2       15602             Grumpier Old Men
3       31357            Waiting to Exhale
4       11862  Father of the Bride Part II
...       ...                          ...
32837  390959    Shadow of the Blair Witch
32838  289923          The Burkittsville 7
32839  222848              Caged Heat 3000
32840  111109          Century of Birthing
32841  461257                     Queerama

[32831 rows x 2 columns]

In [11]:
from sklearn.metrics.pairwise import cosine_similarity

top_k = 10
row_idx = df.index[df['id'] == 141210][0]
sim = cosine_similarity(vectors[row_idx], vectors).flatten()
top_indices = np.argsort(sim)[-top_k-1:-1][::-1]

df.iloc[top_indices]['title']

18558                    John Mulaney: New In Town
32312             The Gerber Syndrome: Il Contagio
19755                      When Good Ghouls Go Bad
20624                    Doug Benson: Doug Dynasty
22921                            Chris Tucker Live
22862    Chelsea Handler Uganda Be Kidding Me Live
32642                    Chris D'Elia: Man on Fire
8688                                  Blood Trails
30701                            Josh Blue: Delete
29895                  Lisa Lampanelli: Dirty Girl
Name: title, dtype: object

In [12]:
# def recommend_top_n_movies(top_n : int, movie_name : str):
#     if movie_name not in new_df['title'].values:
#         print(f"Movie '{movie_name}' not found in the database.")
#         return
#     movie_index = new_df[new_df['title'] == movie_name].index[0]
#     distances = similarity[movie_index]
#     movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:top_n+1]
    
#     for i in movies_list:
#         print(new_df.iloc[i[0]].title)


# recommend_top_n_movies(5, 'Fight Club')

In [13]:
movies_map = df.set_index('id')['title'].to_dict()

movies_map = sorted(movies_map.items(), key = lambda x : x[1])

# with open("../src/constants/__init__.py", "a", encoding="utf-8") as f:
#     f.write('{')
#     for k, v in movies_map:
#         f.write(f'''    {k}: "{v.replace('"', '')}",\n''')
#     f.write('} # type: ignore')

In [22]:
for index in [2518.0, 11214.0, 17665.0, 17663.0, 15882.0, 18517.0, 18515.0, 13716.0, 26225.0, 18448.0]:
    print(df[df.index == index]['title'])

2518    Toy Story 2
Name: title, dtype: object
11214    Dhoondte Reh Jaoge
Name: title, dtype: object
17665    Charlotte's Web 2: Wilbur's Great Adventure
Name: title, dtype: object
17663    Copenhagen
Name: title, dtype: object
15882    Ender's Game
Name: title, dtype: object
18517    The Invisible Boy
Name: title, dtype: object
18515    Ghost Son
Name: title, dtype: object
13716    A Map For Saturday
Name: title, dtype: object
26225    Details
Name: title, dtype: object
18448    Let's Kill Ward's Wife
Name: title, dtype: object